apiVersion: v1
kind: Service
metadata:
  namespace: intelops_compge_testing
  labels:
    app: intelops_compge_testing
  name: intelops_compge_testing
spec:
  ports:
  
    - protocol: TCP
      port: 9876
      targetPort: 9876
   
   
  selector:
    app: intelops_compge_testing
  type: ClusterIP
